run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # Enabled by default, see https://golangci-lint.run/usage/linters#enabled-by-default
    # - deadcode  # deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    # - structcheck # deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.
    - typecheck
    - unused
    # - varcheck # deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.
    - goimports
    - gofmt
    - gocritic
# issues:
#   exclude-rules:
#     - path: magefile\.go
#       linters:
#         - deadcode
